
service: aws-iot-lambda

custom:
  defaultRegion: ap-northeast-1

provider:
  name: aws
  runtime: python3.9
  region: ${opt:region, self:custom.defaultRegion}

functions:
  deviceInfo:
    handler: src/handler.lambda_handler
